### PR TITLE
feat: allow array in search function

### PR DESCRIPTION
**Pull request by sanding0**
currently the search function accept only one directory, this patch allows mutiple directory where can search start.

### CODE REVIEW

**Comment by sanding0** [comment]
@davidtheclark could u plz review this pr

**Comment by 4lch4** [comment]
Hey @sanding0 I'll take a look at this for ya and get back to you.

**Comment by 4lch4** [comment]
It's an excellent submission, but adding line 16 means the code doesn't meet the testing requirements. So I'm trying to find a way to test this line without too much extra work.

**Comment by 4lch4** [comment]
I've not forgotten to do this, I just haven't been able to figure it out. I'm not the most familiar with testing (I know, bad developer) so I'm trying to learn what I can to make this work ^_^

**Review by d-fischer — CHANGES_REQUESTED** [review]
Indeed this needs some tests. The code looks fine, but without tests, I'm not accepting this.

**Comment by d-fischer** [comment]
Due to many changes in the code structure and to how searching works on the v9 branch, this PR is now massively outdated. If there is still interest in this feature, I would recommend a reimplementation from scratch in a new PR.

**Pull request closed without merging**
